# Generated by Django 5.2.16 on 2026-07-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSNAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('psn_id', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('NA', 'North America'), ('EU', 'Europe'), ('IR', 'Iran'), ('AS', 'Asia')], default='IR', max_length=2)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psn_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_accounts_psnaccount',
                'ordering': ['-added_at'],
            },
        ),
    ]
