# Generated by Django 5.2.16 on 2026-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('tier', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.TextField()),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PS5Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=512)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('igdb_id', models.IntegerField(blank=True, null=True)),
                ('igdb_name', models.CharField(blank=True, max_length=512, null=True)),
                ('genre_label', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ps5_games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
    ]
