# Generated by Django 5.2.16 on 2026-08-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('pre_purchase', 'Before Purchase'), ('post_purchase', 'After Purchase'), ('account', 'Account'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
